version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: fatihtuzlu
      POSTGRES_PASSWORD: fatihtuzlu123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://fatihtuzlu:fatihtuzlu123@postgres:5432/booking

volumes:
  postgres_data:
